=== EunV/XMLlecture/chap04/ex4-7.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://skuniv.ac.kr/cs/yoon/audio" 
        xmlns:myAudio="http://skuniv.ac.kr/cs/yoon/audio" 
        elementFormDefault="qualified">
   
    <!-- PlayTime 요소 관련 정의-->
    <simpleType name="hourScope">
        <restriction base="int">
            <minInclusive value="0" />
            <maxExclusive value="10" />
        </restriction>
    </simpleType>

    <simpleType name="secondScope">
        <restriction base="int">
            <minInclusive value="0" />
            <maxExclusive value="60" />
        </restriction>
    </simpleType>

    <simpleType name="minuteScope">
        <restriction base="int">
            <minInclusive value="0" />
            <maxExclusive value="60" />
        </restriction>
    </simpleType>

    <group name="TimeGroup">
        <sequence>
            <element name="hours" type="myAudio:hourScope" />
            <element name="minutes" type="myAudio:minuteScope" />
            <element name="seconds" type="myAudio:secondScope" />
        </sequence>
    </group>

    <complexType name="PlayTimeType">
        <group ref="myAudio:TimeGroup" />
    </complexType>
    <!-- PlayTime 요소 관련 정의 끝-->

    <group name="AlbumGroup">
        <sequence>
            <element name="Artist" type="string" />
            <element name="Title" type="string" />
            <element name="Genre" type="string" />
            <element name="Released-date" type="string" />
            <element name="Song" maxOccurs="unbounded">
                <complexType mixed="true">
                    <sequence>
                        <element name="playTime" type="myAudio:PlayTimeType"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </group>

    <complexType name="AlbumType">
        <group ref="myAudio:AlbumGroup" />
    </complexType>

    <element name="AudioCatalog">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="Cd" type="myAudio:AlbumType"/>
                <element name="Cassette" type="myAudio:AlbumType"/>
                <element name="Record" type="myAudio:AlbumType"/>
                <element name="Mp3" type="myAudio:AlbumType"/>
            </choice>
        </complexType>
    </element>
</schema>

=== EunV/XMLlecture/chap04/ex4-7.xml
<?xml version="1.0" encoding="UTF-8"?>
<AudioCatalog 
        xmlns="http://skuniv.ac.kr/cs/yoon/audio" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://skuniv.ac.kr/cs/yoon/audio ex4-7.xsd">

    <Cd>
        <Artist>홍길동</Artist>
        <Title>오늘</Title>
        <Genre>재즈</Genre>
        <Released-date>2020-10-14</Released-date>
        <Song>
            아침밥
            <playTime>
                <hours>0</hours>
                <minutes>3</minutes>
                <seconds>30</seconds>
            </playTime>
        </Song>
        <Song>
            점심의 커피
            <playTime>
                <hours>0</hours>
                <minutes>4</minutes>
                <seconds>27</seconds>
            </playTime>
        </Song>
    </Cd>

    <Cassette>
        <Artist>메론</Artist>
        <Title>OurLove</Title>
        <Genre>락</Genre>
        <Released-date>2010-10-14</Released-date>
        <Song>
            Paint
            <playTime>
                <hours>0</hours>
                <minutes>7</minutes>
                <seconds>20</seconds>
            </playTime>
        </Song>

        <Song>
            Favor
            <playTime>
                <hours>0</hours>
                <minutes>3</minutes>
                <seconds>45</seconds>
            </playTime>
        </Song>
    </Cassette>

    <Mp3>
        <Artist>찰리</Artist>
        <Title>Alone</Title>
        <Genre>발라드</Genre>
        <Released-date>2020-01-01</Released-date>
        <Song>
            You're so beautiful
            <playTime>
                <hours>0</hours>
                <minutes>7</minutes>
                <seconds>59</seconds>
            </playTime>
        </Song>
    </Mp3>

    <Record>
        <Artist>다니엘 리</Artist>
        <Title>Salary Man</Title>
        <Genre>클래식</Genre>
        <Released-date>2008-01-23</Released-date>
        <Song>
            빛나는 강
            <playTime>
                <hours>1</hours>
                <minutes>2</minutes>
                <seconds>22</seconds>
            </playTime>
        </Song>
    </Record>
</AudioCatalog>
